apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins-app.fullname" . }}
  labels:
    app: jenkins-server
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "jenkins-app.labels" . | nindent 4 }}
